### ISSUE TITLE
Doesn't compile for VS2015

### ISSUE THREAD

**Issue by MikeMarcin** [pdimov/mp11#1]
Trivial program doesn't compile with MSVC 2015 Update 3 and Boost 1.62.0

`#include <boost/mp11.hpp>
int main() {
}`

Did BOOST_NO_CXX11_CONSTEXPR change perhaps?

> 1>C:\code\mp11\include\boost/mp11/algorithm.hpp(117): warning C4346: 'std::is_same<T,V>::value': dependent name is not a
1>type
1>  C:\code\mp11\include\boost/mp11/algorithm.hpp(117): note: prefix with 'typename' to indicate a type
1>  C:\code\mp11\include\boost/mp11/algorithm.hpp(118): note: see reference to class template instantiation 'boost::detai
1>  l::mp_count_impl<L<T...>,V>' being compiled
1>C:\code\mp11\include\boost/mp11/algorithm.hpp(117): error C2059: syntax error: '...'
1>C:\code\mp11\include\boost/mp11/algorithm.hpp(117): error C2976: 'boost::mp_size_t': too few template arguments
1>  C:\code\mp11\include\boost/mp11/integral.hpp(30): note: see declaration of 'boost::mp_size_t'
1>C:\code\mp11\include\boost/mp11/algorithm.hpp(143): warning C4346: 'std::integral_constant<bool,B>::value': dependent n
1>ame is not a type
1>  C:\code\mp11\include\boost/mp11/algorithm.hpp(143): note: prefix with 'typename' to indicate a type
1>  C:\code\mp11\include\boost/mp11/algorithm.hpp(144): note: see reference to class template instantiation 'boost::detai
1>  l::mp_count_if_impl<L<T...>,P>' being compiled
1>C:\code\mp11\include\boost/mp11/algorithm.hpp(143): error C2059: syntax error: '...'
1>C:\code\mp11\include\boost/mp11/algorithm.hpp(143): error C2976: 'boost::mp_size_t': too few template arguments
1>  C:\code\mp11\include\boost/mp11/integral.hpp(30): note: see declaration of 'boost::mp_size_t'

**Comment by pdimov** [comment]
Interesting. Works with Update 2.

**Comment by pdimov** [comment]
Yes, it's the `BOOST_NO_CXX11_CONSTEXPR` macro; `visualc.hpp` line 185:

```
// C++11 features supported by VC++ 14 update 3 (aka 2015)
//
#if (_MSC_FULL_VER < 190024210)
#  define BOOST_NO_CXX14_VARIABLE_TEMPLATES
#  define BOOST_NO_SFINAE_EXPR
#  define BOOST_NO_CXX11_CONSTEXPR
#endif
```

**Comment by pdimov** [comment]
Should be fixed now.

**Comment by MikeMarcin** [comment]
It is, thanks!
